baseurl      = "https://rosharp.github.io/"
languageCode = "en-us"
theme        = "cactus"
paginate     = 10

[taxonomies]
category = "blog"
tag      = "tags"
series   = "series"

[languages]
[languages.en]
title = "Palenight Blues"
subtitle = "Blog about music and code"
keywords = ""
copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'

[params]
colortheme = "dark" # dark, light, white, or classic
description = "Here I write about Linux and other tech related stuff."
mainSectionTitle = "Posts"
showAllPostsOnHomePage = true
postsOnHomePage = 5
tagsOverview = true
rss = true

[[params.social]]
name = "github"
link = "https://github.com/rosharp"

[[params.social]]
name = "email"
link = "vy.bekshnev@gmail.com" # no need for "mailto:" at the start

[markup]
[markup.highlight]
codeFences = true
guessSyntax = false
hl_Lines = ""
lineNoStart = 1
lineNos = false
lineNumbersInTable = true
noClasses = true
style = "monokai"
tabWidth = 4

# And you can even create generic menu
[[menu.main]]
name       = "Home"
url        = "/"
weight     = 1

[[menu.main]]
name = "Posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3
