baseurl      = "https://rosharp.github.io/"
title        = "My Blog"
languageCode = "en-us"
theme        = "cactus"
paginate     = 10

[params]
dateform        = "Jan 2, 2006"
dateformShort   = "Jan 2"
dateformNum     = "2006-01-02"
dateformNumTime = "2006-01-02 15:04"

# Subtitle for home
homeSubtitle = "Music and Code"

# Set disableReadOtherPosts to true in order to hide the links to other posts.
disableReadOtherPosts = false

# Enable sharing buttons, if you like
enableSharingButtons = true

# Metadata mostly used in document's head
description = "My new homepage or blog"
keywords = "homepage, blog"
images = [""]

[taxonomies]
category = "blog"
tag      = "tags"
series   = "series"

[languages]
[languages.en]
title = "Palenight Blues"
subtitle = "Blog about music and code"
keywords = ""
copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
readOtherPosts = "Read other posts"

[languages.en.params.logo]
logoText = "Ro Sharp"
logoHomeLink = "/"
# or
#
# path = "/img/your-example-logo.svg"
# alt = "Your example logo alt text"
[params]
colortheme = "classic" # dark, light, white, or classic
description = "Hugo is a general-purpose website framework. Technically speaking, Hugo is a static site generator. Unlike systems that dynamically build a page with each visitor request, Hugo builds pages when you create or update your content. Since websites are viewed far more often than they are edited, Hugo is designed to provide an optimal viewing experience for your website’s end users and an ideal writing experience for website authors."
mainSectionTitle = "Blog"
showAllPostsOnHomePage = true
postsOnHomePage = 5
tagsOverview = true

[[params.social]]
name = "github"
link = "https://github.com/monkeyWzr"

[[params.social]]
name = "email"
link = "monkeywzr@gmail.com" # no need for "mailto:" at the start

[[params.social]]
name = "linkedin"
link = "https://www.linkedin.com/in/monkeywzr/"

[markup]
[markup.highlight]
codeFences = true
guessSyntax = false
hl_Lines = ""
lineNoStart = 1
lineNos = false
lineNumbersInTable = true
noClasses = true
style = "monokai"
tabWidth = 4
[params]
rss = true

# And you can even create generic menu
[[menu.main]]
identifier = "blog"
name       = "Blog"
url        = "/posts"
